# Generated by Django 5.2.2 on 2025-06-10 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Song", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="genre",
        ),
        migrations.CreateModel(
            name="SongAndGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genre",
                        to="Song.genre",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="song",
                        to="Song.song",
                    ),
                ),
            ],
            options={
                "unique_together": {("song", "genre")},
            },
        ),
    ]
