# Generated by Django 5.2.2 on 2025-06-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Song", "0002_remove_song_genre_songandgenre"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="genres",
            field=models.ManyToManyField(related_name="songs", to="Song.genre"),
        ),
        migrations.DeleteModel(
            name="SongAndGenre",
        ),
    ]
